version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080 # replace with OpenFaaS gateway address
functions:
  HadnleStr:
    lang: python3-flask
    handler: ../functions/HadnleStr
    image: asueeer/handle_str


  
